name: Build TrollFolls injection

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-14
    env:
      THEOS: ${{ github.workspace }}/theos
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3'
    
    - name: Setup Theos
      uses: actions/checkout@v4
      with:
         repository: theos/theos
         path: ${{ github.workspace }}/theos
         submodules: recursive

    - name: Install Dependencies
      run: |
        brew install make dpkg ldid
        echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

    - name: Copy SwiftProtobuf (rootless)
      run: |
        mkdir swiftprotobuf-rootless && cd "$_"
        wget https://github.com/whoeevee/EeveeSpotify/releases/download/swift2.0/org.swift.protobuf.swiftprotobuf_1.26.0_iphoneos-arm64.deb
        ar -x org.swift.protobuf.swiftprotobuf_1.26.0_iphoneos-arm64.deb
        tar -xvf data.tar.lzma
        cp -r var/jb/Library/Frameworks/SwiftProtobuf.framework $THEOS/lib/iphone/rootless

    - name: Build EeveeSpotify (rootless)
      run: |
        make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
        echo "filename=$(find . -name '*arm64*' -path './packages/*' | cut -d/ -f3)" >> $GITHUB_ENV
        find $THEOS -iname "Orion*"
        ls -la ./packages/
        ls -la $THEOS/lib/iphone/rootless
        mkdir trollfools
        mkdir com.eevee.spotify && cd "$_"
        cp "./packages/${{ env.filename }}" .
        ar -x "${{ env.filename }}"
        tar -xvf data.tar.lzma
        cd ..
        find com.eevee.spotify/ \( -name "*.bundle" -o -name "*.framework" -o -name "*.dylib" \) | xargs -I {} cp -r {} ./trollfools/
        cp -r var/jb/Library/Frameworks/SwiftProtobuf.framework trollfools
        cp -r $THEOS/lib/iphone/rootless/Orion.framework trollfools
        cd trollfools
        zip -r "../${{ env.filename }}.zip" *
        ls -la ../
